---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: paven-persistence-utils
  annotations:
#    backstage.io/source-location: url:https://github.com/Round-Feather/paven-core-vehicles-service
    backstage.io/techdocs-ref: dir:.
    google.com/cloudbuild-project-slug: paven-common-v3
    google.com/cloudbuild-location: global
    sonarqube.org/project-key: Round-Feather_paven-persistence-utils_AZFQ_wKnmpqdTNJ_C8m9
  links:
    - url: https://roundfeather-paven.atlassian.net/wiki/x/AYCsNQ
      title: Confluence
spec:
  type: library
  lifecycle: production
  owner: guests